### ISSUE TITLE
Flickering grass colours / weird lines in grass colors (8.2)

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#376] opened 2019-11-17 22:49 UTC
I'm seeing this kind of thing quite commonly - grass colours flickering to other colours when exploring a world (using forge, have not tested to see if the same issue affects Spigot servers when the client is installed):

https://streamable.com/sd5pr

Edit: Forgot to mention im using v8.3_r1

**Comment by Frontear** [comment] 2019-11-18 00:43
Are you sure that this is from OTG? I've seen very similar behaviour from shaders on vanilla minecraft

**Comment by MCPitman** [comment] 2019-11-18 01:06
Yes, it doesn't happen in v6 OTG and I wasn't using shaders.

It's the grass colours that are changing, you can see it more obviously in biomes with contrasting colours.

**Comment by PG85** [comment] 2020-01-17 22:38
Been flying around BB and wildlands for a while, most biomes have solid colors, swampland has a gradient but appears to work fine. Need a preset, seed and coords for this. Also need to know optifine yes/no, shaders (internal?) etc. Moving to support for now, can look at this after v9 if necessary.

**Comment by PG85** [comment] 2020-01-17 22:41
See also #298 for weird lines in grass colors.

**Comment by Darsenia** [comment] 2020-01-30 19:29
I can confirm this issue too.This started happen only in v8+(v6 was working good)
It also happens to foliage colours, and it happens in every world.
Preset - Traveler's Dream
No shaders,with or without Optifine.
Sometimes one block/line, sometimes the whole chunk.Dissapears after a few seconds.
![2020-01-30_22 25 46](https://user-images.githubusercontent.com/36276289/73483089-f19a9900-43af-11ea-8b73-824b5563fee8.png)

**Comment by PG85** [comment] 2020-01-31 10:20
I have not ever seen this in-dev (without optifine), can confirm this happens for real client with optifine though.

**Comment by Genovvaa** [comment] 2020-02-12 22:16
i can confirm that this bug occurs without optifine. world was created with optifine installed however i removed it(and everything else except OTG and BB) and generated new chunks and this still persists as seen here. it is not as... aggressive, as the video above however. 
![image](https://user-images.githubusercontent.com/60989445/74382206-f18c9700-4dba-11ea-8aa2-1e32c99c7f08.png)

**Comment by PG85** [comment] 2020-02-13 00:50
I've seen that:
- For Forge, it doesn't seem to disappear by itself.
- With Optifine it happens a lot more often.
- After causing a block update, it's fixed.
- For Spigot, I can see wrong colors when newly generated chunks are being rendered but it almost instantly fixes itself.

I'd like to know:
- For Forge, is it fixed after leaving/rejoining?
- Is it reliably reproducible or completely random?
- Is there anything special going on with the biomes/settings where this happens? Does it only happen in certain types of biomes (virtual/custom?).

Atm I can't do much about this except guess that there's missing lighting updates or that biome colors are not being updated correctly on the client for some reason. Need more info.

**Comment by Genovvaa** [comment] 2020-02-13 00:59
it does fix itself after reloading the world however its just the same as if the blocks got updates and it reappears elsewhere. (after about 2-3 minutes ive seen it disappear without touching any nearby blocks)

its completely random as in where and when it will show but generally ive found it on biome borders. as long as there are 2 biomes touching, it will exist nearby

as far as i can tell its in every biome, from ForestEnd (that blue biome ive only seen once) to savannah and tundra

my guess is that it **is** biome colours not being updated correctly
![2020-02-12_19 58 35](https://user-images.githubusercontent.com/60989445/74391393-1d674700-4dd2-11ea-9dc3-0c3b6d9d9c98.png)

**Comment by croftyraider** [comment] 2020-02-17 01:05
Same version of OTG with biome bundle, added to the OmniFactory modpack and I've seen the exact same issue. Seems to be a rendering glitch as standing on top of the incorrect grass block yields the same biome information (from the F3 screen) as an adjacent block.

Also, I've seen this in water as well, so it's not just grass.

**Comment by PG85** [comment] 2020-02-18 13:31
Thanks folks, should hopefully be fixed for v9.0_r7, to be released on the disc as soon as I figure out this dang optifine fog bug.

**Closed as completed by PG85** 2020-02-18 13:31 UTC
Labels: Bug - Issue, Forge, Mod Compatibility, World/Biome/Terrain
