### ISSUE TITLE
[Spigot]Biome ID #XX returns custom biome #XX instead of its own. [When Using Multiple worlds]

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#150] opened 2018-03-25 16:56 UTC
It Appears that OTG gets problems when using Multiple Worlds on Spigot 1.12.2.

(Tested with BiomeBundle)

If you Add just one instance of Biome Bundle to the world, it works fine. Creating new OTG worlds (without any kind of Presets) also works fine. Though I didn´t test tweaking them.

However upon adding another World with the BiomeBundle Preset (Correctly Installed) the worldGenerator fails with the Error mentioned in the Title.

```
[16:37:12] [Server thread/WARN]: Unexpected exception while parsing console command "mv create BiomeBundle2 NORMAL -g OpenTerrainGenerator"
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.6.0-SNAPSHOT-b736
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.AssertionError: Biome ID #158 returns custom biome #405 instead of its own.
	at com.pg85.otg.bukkit.OTGBiomeBase.checkRegistry(OTGBiomeBase.java:153) ~[?:?]
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:141) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	... 8 more
```
Here in Long. This error is not Related to Multiverse, as this also Happens when the World is Registered in the Bukkit.yml

I have no Idea why, or how this comes up. But this problem have at least two others.
(Tested on Java 1.8)

**Comment by ccorp2002** [comment] 2018-03-25 21:02
I also used to have that problem... I just changed the biome ID for each biome... it took forever. DO NOT TRY (Unless you have like an hour and a half...)

**Comment by ccorp2002** [comment] 2018-03-25 21:07
It was grueling... It wasn't exactly worth the finished product. changing 300+ biome IDs by hand in notepad++. Not gonna do it again.

**Comment by LanToaster** [comment] 2018-03-25 22:57
Hmm, the Error Message is Misleading.
I apologize then for Creating this "NonIssue", as in that case its just a ID conflict. 

What even got me to trying out were people who had Problems adding SkyLands or other worlds.

**Comment by LanToaster** [comment] 2018-03-25 23:00
Well, maybe one should adjust the ErrorMessage in this case, when I think about it. 
Also, Its stupid when I want to use the same Biome in two worlds that they need to have Different BiomeIDs Oo

**Comment by MCPitman** [comment] 2018-04-01 21:43
Dynamic biome ID assignment is coming in a future patch and should resolve this and any other ID related issues.

**Comment by LanToaster** [comment] 2018-04-02 18:35
Awesome. :D 

That would mean, we only Supply a list of Biomes without IDs? Thats really Awesome!

**Comment by sfwr** [comment] 2018-04-08 15:59
@LanToaster how'd you fix this?

**Comment by LanToaster** [comment] 2018-04-11 18:31
I didn´t fix it. As it isnt a Problem for me. 
The Problem appears to be a ID conflict when you have the same ID assigned for Custom Biomes on different worlds (IIRC). 
I dont use Presets, so my IDs usually dont conflict anyway.

**Comment by FrakTech** [comment] 2018-11-05 20:07
I'm having this same issue. It happens both with BiomeBundle and Skylands for OTG.

I install OTG correctly for the first world using Biome Bundle (Renamed in OTG world folder to Homeland). This works perfectly.

I then installed Skylands to the otg/world forlder (renamed to Skyland). As well as edit bukkit.yml for the world name and generator to match the Skyland folder in otg/world.

Issue command: mv create Skyland normal -g OpenTerrainGenerator and get the following error:

>mv create Skyland normal -g OpenTerrainGenerator
[11:56:11 INFO]: [OTG] 62 biomes Loaded
[11:56:11 INFO]: CONSOLE: Starting creation of world 'Skyland'...
[11:56:12 WARN]: Unexpected exception while parsing console command "mv create Skyland normal -g OpenTerrainGenerator"
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.5-b719
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.AssertionError: Biome ID #158 returns custom biome #405 instead of its own.
        at com.pg85.otg.bukkit.OTGBiomeBase.checkRegistry(OTGBiomeBase.java:153) ~[?:?]
        at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:141) ~[?:?]
        at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
        at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
        at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
        at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
        at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot.jar:git-Spigot-fc7ad59-d7bebef]
        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fc7ad59-d7bebef]
        ... 8 more

When having this issue with Biome Bundle I know it has to do with the id. What I don't understand is why it is having the same issue with Skyland. I looked in the config for Skylands and none of the biome id are the same. Id 405 isn't even referenced.

I'm not programmer. Just trying to report my experience and see if there is any hope. I would love to have multiple worlds on my server using otg and biome bundel along with skyland.

If anyone knows of any suggestions I would greatly appreciate it. Thank You.

**Comment by LanToaster** [comment] 2018-11-06 07:33
Are the IDs of your SkyLands below 256, and use ReplaceToBiomename?

If yes, change the IDs to a Unique ID above 256

**Comment by FrakTech** [comment] 2018-11-06 20:39
That's the odd thing. The Id's from what I could tell were all way above 256

**Comment by PG85** [comment] 2019-06-09 22:24
Should be fixed with v7, needs testing.

**Closed as completed** 2019-08-05 09:46 UTC
Labels: Bug - Issue, Spigot/Paper, World/Biome/Terrain
