### ISSUE TITLE
[Bug/compatibility issue] - crash when using portal with RandomPortals

### ISSUE THREAD

**Issue by pimalel233** [PG85/OpenTerrainGenerator#395] opened 2019-12-08 21:10 UTC
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x ] Other - specify here
OpenTerrainGenerator-1.12.2+-+v8.3.jar

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]

14.23.5.2838
--

#### What other plugins are you running?
Animania-1.12.2-1.7.3.jar
AppleCore-MC1.12.2-3.2.0.jar
AppleSkin-MC1.12-1.0.9.jar
Aquaculture-1.12.2-1.6.8.jar
AutoRegLib-1.3-32.jar
BASE-1.12.2-3.13.0.jar
Baubles-1.12-1.5.2.jar
BearWithMe-1.12.2-1.3.1.jar
Better-Underground-Mod-1.12.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
BetterFoliage-MC1.12-2.2.0.jar
BetterWithMods-1.12-2.3.20-1037.jar
BiomesOPlenty-1.12.2-7.0.1.2443-Universal.jar
BiomeTweaker-1.12.2-3.2.354.jar
BiomeTweakerCore-1.12.2-1.0.39.jar
Bloodmoon-MC1.12.2-1.5.3.jar
Ceramics-1.12-1.3.7.jar
Champions-1.12.2-1.0.11.jar
CherishedWorlds-1.12.2-1.0.1.jar
ChiselsAndBits-14.33.jar
ChunkAnimator-MC1.12-1.2.jar
ClientTweaks_1.12.2-3.1.11.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-Universal.jar
CoFHCore-1.12.2-4.6.3.27-Universal.jar
Comforts-1.12.2-1.4.1.2.jar
ConArm-1.12.2-1.2.5.3.jar
Controlling-3.0.7.jar
CoralReef-2.5-1.12.2.jar
CraftStudioAPI-Universal-1.0.1.95-MC1.12-Alpha.jar
CraftTweaker2-1.12-4.1.19.jar
CreativeCore_v1.9.71_MC1.12.2.jar
DocumentYourModMod-1.2.0.jar
DynamicSurroundings-1.12.2-3.6.0.2.jar
Erebus-1.0.31.jar
Essentials-1.12.2-1.2.1.jar
Exotic+Birds+1.12.2-3.1.0.jar
FamiliarFauna-1.12.2-1.0.11.jar
FastFurnace-1.12.2-1.3.1.jar
FastWorkbench-1.12.2-1.7.2.jar
Ferdinand's+Flowers-1.12.X-1.10.4.1.jar
FlatColoredBlocks-MC1.12-6.8.jar
Flood-1.0.1.jar
Forgelin-1.8.4.jar
HardcoreDarkness-MC1.12.2-2.0.jar
Hwyla-1.8.26-B41_1.12.2.jar
InfernalMobs-1.12.2.jar
Inspirations-1.12.2-0.2.8.jar
ItemPhysic_Full_1.4.27_MC1.12.2.jar
JEIIntegration_1.12.2-1.5.1.36.jar
JEI_1.12.2-4.15.0.292.jar
JJ+Coats+of+Arms+1.12-1.12.2-v1.0.9.jar
JustEnoughResources-1.12.2-0.8.9.48.jar
Mantle-1.12-1.3.3.55.jar
ModTweaker-4.0.17.jar
MTLib-3.0.6.jar
MultithreadedNoise-1.12.2-0.0.2.jar
Natura-1.12.2-4.3.2.69.jar
NoRecipeBook_v1.2.2forMC1.12.2.jar
NotEnoughItems-1.12.2-2.4.3.245-Universal.jar
Nutrition-1.12.2-4.4.0.jar
OpenTerrainGenerator-1.12.2+-+v8.3.jar
OptiFine_1.12.2_HD_U_F4.jar
OreLib-1.12.2-3.6.0.1.jar
Pam's+Get+all+the+Seeds!+1.12a.jar
Placebo-1.12.2-1.6.0.jar
Plants-1.12.2-2.10.7.jar
Platforms-1.12.0-1.4.6.jar
PotionFingers-R1.0-8.jar
ProjectVibrantJourneys-1.12.2-1.6.4.jar
ProportionalDestructionParticles-1.12.2-1.2.4.jar
Quark-R1.6-177.jar
Railcraft-12.0.0.jar
RandomConfigs-1.12.2-1.3.2.3.jar
RandomPatches-1.12.2-1.19.1.1.jar
RandomPortals-1.12.2-1.8.1.1.jar
RandomTweaks-1.12.2-2.7.1.0.jar
RedstoneFlux-1.12-2.1.0.6-Universal.jar
RPIntegration-1.12.2-1.5.1.0.jar
Rustic-1.1.1.jar
ScalingHealth-1.12.2-1.3.42+147.jar
SereneSeasons-1.12.2-1.2.18-Universal.jar
ShetiPhianCore-1.12.0-3.5.9.jar
SilentLib-1.12.2-3.0.13+167.jar
SimplyTea-1.6.jar
SlideemAll-1.03.jar
SmoothFont-MC1.12.2-2.1.1.jar
SnowAccumulation-1.12-1.0.0.jar
TConstruct-1.12.2-2.13.0.171.jar
TheBetweenlands-3.5.4-Universal.jar
TinkersComplement-1.12.2-0.4.2.jar
Toast+Control-1.12.2-1.8.1.jar
Tombstone-3.6.2-1.12.2.jar
ToolBelt-1.12.2-1.9.12.jar
Totemic-1.12.2-0.11.6.jar
ToughAsNails-1.12.2-3.1.0.141-Universal.jar
TreeTweaker-1.6.1.jar
TwilightForest-1.12.2-3.10.1013-Universal.jar
TwistedTweaks-0.7.0-6.jar
Waddles-1.12.2-0.6.0.jar
WAIM-1.0.0.jar
Wawla-1.12.2-2.5.273.jar
[1.12]ArmorStatusHUD-Client-1.43.0.jar
[1.12]bspkrsCore-Universal-7.6.0.1.jar
[1.12]StatusEffectHUD-Client-1.43.0.jar

#### Description
Game is crashing when entering portal when OTG is combined with a mod RandomPortals. Once I remove RandomPortals or OTG from my modlist, portal works.

Build normal obsidian portal, activate it, enter.

[crash-2019-12-08_22.00.43-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3937163/crash-2019-12-08_22.00.43-server.txt)

**Comment by PG85** [comment] 2020-01-08 14:02
Hey @pimalel233 , thanks for reporting this and sorry for the late reply (holidays). Some problems are still to be expected when combining portal-management mods with OTG for Forge, since OTG has its own features for creating/deleting dimensions and managing portals. Moving to backlog atm, to be picked up as soon as higher prio things have been fixed.

**Comment by PG85** [comment] 2020-01-18 08:56
Hey @pimalel233 , the error seems to be coming from RP code. I've checked their repo but the line numbers don't match up anymore, there's no code there that should be affected by OTG. That being said, OTG's dimension features do hack into a few things, so the root of the problem may be elsewhere. Please test this with the newest version of RP and also file a bug with RP. You can let them know the cause may very well be on the OTG side, but I need more information since the error is happening in RP code. Closing for now, feel free to reopen or create a new ticket when the problem can be traced back to OTG, thanks!

**Closed as completed by PG85** 2020-01-18 08:56 UTC
Labels: Forge, Mod Compatibility, Dimensions, Bug - Crash
