### ISSUE TITLE
Thermal Foundation: Server crash when generating new chunks. Ore spawning 

### ISSUE THREAD

**Issue by weedgoku** [PG85/OpenTerrainGenerator#223] opened 2019-01-13 23:39 UTC
Some context: I have removed and hidden many Thermal Foundation ores from JEI, but they still generate in the world. The crash occurred when I was flying around in creative mode generating many new chunks. The multiMC log from the game session contains many lines saying `[09:46:48] [Server thread/INFO] [OTG]: Double population prevented` shortly before the crash, and right afterwards, `[09:49:09] [Server thread/INFO] [OTG]: SaveToDisk waiting on Populate. Although other mods could be causing this and there may not be any problem, this can potentially cause an endless loop!`

### crash-2019-01-14_09.49.08-server.txt

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  OTGCorePlugin (OTG-Core.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/14/19 9:49 AM
Description: Exception ticking world

java.lang.RuntimeException: Whatever it is you're trying to do, we didn't write any code for it (sorry). Please contact Team OTG about this crash.
	at com.pg85.otg.forge.ForgeWorld.setBlock(ForgeWorld.java:841)
	at com.pg85.otg.generator.resource.OreGen.spawn(OreGen.java:128)
	at com.pg85.otg.generator.resource.Resource.spawnInChunk(Resource.java:195)
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152)
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259)
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:203)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pg85.otg.forge.ForgeWorld.setBlock(ForgeWorld.java:841)
	at com.pg85.otg.generator.resource.OreGen.spawn(OreGen.java:128)
	at com.pg85.otg.generator.resource.Resource.spawnInChunk(Resource.java:195)
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152)
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259)
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:203)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: Biome Bundle
	All players: 1 total; [EntityPlayerMP['weedgoku'/463, l='Biome Bundle', x=-1672.27, y=135.87, z=-2005.32]]
	Chunk stats: ServerChunkCache: 525 Drop: 0
	Level seed: 5919606959195454515
	Level generator: ID 06 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (-1331,64,-229), Chunk: (at 13,4,11 in -84,-15; contains blocks -1344,0,-240 to -1329,255,-225), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 442708 game time, 3554 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 7057 (now: true), thunder time: 171 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.16.0-40-generic
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 400720472 bytes (382 MB) / 2813329408 bytes (2683 MB) up to 2982674432 bytes (2844 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx3200m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                          | Signature                                |
	|:------ |:-------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2796-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2796      | forge-1.12.2-14.23.5.2796-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | otgcore              | 1.12.2 - v7       | minecraft.jar                                   | None                                     |
	| LCHIJA | applecore            | 3.1.4             | AppleCore-mc1.12.2-3.1.4.jar                    | None                                     |
	| LCHIJA | jei                  | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                       | None                                     |
	| LCHIJA | appleskin            | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LCHIJA | crafttweaker         | 4.1.13            | CraftTweaker2-1.12-4.1.13.jar                   | None                                     |
	| LCHIJA | base                 | 3.11.0            | base-1.12.2-3.11.0.jar                          | None                                     |
	| LCHIJA | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | openterraingenerator | v6                | OpenTerrainGenerator-1.12.2+-+v6.jar            | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LCHIJA | biomebundle          | 5.1               | Biome_Bundle-1.12.2-v6.1.jar                    | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| LCHIJA | chiselsandbits       | 14.29             | chiselsandbits-14.29.jar                        | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore             | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| LCHIJA | cofhworld            | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | contenttweaker       | 1.12.2-4.9.1      | ContentTweaker-1.12.2-4.9.1.jar                 | None                                     |
	| LCHIJA | cookingforblockheads | 6.4.65            | CookingForBlockheads_1.12.2-6.4.65.jar          | None                                     |
	| LCHIJA | ctgui                | 1.0.0             | CraftTweaker2-1.12-4.1.13.jar                   | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.2             | CraftTweaker2-1.12-4.1.13.jar                   | None                                     |
	| LCHIJA | ding                 | 1.0.1             | Ding-1.12.1-1.0.1.jar                           | None                                     |
	| LCHIJA | endercore            | 1.12.2-0.5.43     | EnderCore-1.12.2-0.5.43.jar                     | None                                     |
	| LCHIJA | thermalfoundation    | 2.6.1             | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio              | 5.0.39            | EnderIO-base-1.12.2-5.0.39.jar                  | None                                     |
	| LCHIJA | enderiobase          | 5.0.39            | EnderIO-base-1.12.2-5.0.39.jar                  | None                                     |
	| LCHIJA | enderiomachines      | 5.0.39            | EnderIO-machines-1.12.2-5.0.39.jar              | None                                     |
	| LCHIJA | erebus               | 1.0.25            | Erebus-1.0.25.jar                               | None                                     |
	| LCHIJA | grimoireofgaia       | 1.6.8             | GrimoireOfGaia3-1.12.2-1.6.8.jar                | None                                     |
	| LCHIJA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHIJA | incontrol            | 3.8.2             | incontrol-1.12-3.8.2.jar                        | None                                     |
	| LCHIJA | jeresources          | 0.8.5.27          | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
	| LCHIJA | mapwriter            | 2.8.2             | MapWriter-1.12.2-2.8.2.jar                      | None                                     |
	| LCHIJA | resize               | 1.6               | Resizing+Potion-r1.9.jar                        | None                                     |
	| LCHIJA | solcarrot            | 1.3.1             | solcarrot-1.12.2-1.3.3.jar                      | None                                     |
	| LCHIJA | thermaldynamics      | 2.5.3             | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalinnovation    | 0.3.1             | ThermalInnovation-1.12.2-0.3.1.8-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tombstone            | 3.3.0             | tombstone-3.3.0-1.12.jar                        | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['weedgoku'/463, l='Biome Bundle', x=-1672.27, y=135.87, z=-2005.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by PG85** [comment] 2019-08-21 23:05
Hey @weedgoku, looks like something went wrong when trying to spawn ores, likely because of oregen trying to spawn blocks in unloaded chunks or outside of the chunks currently being populated. If you're using Biome Bundle, its oregen is configured properly to not cause this problem. If you've edited ore gen settings yourself via the biome configs, setting ore size too high may cause this. Join us on the OTG Discord at #openterraingen if you have any questions about that.

This crash may also be caused by the other mods you've mentioned. I've made quite a few changes for v7 and v8 though, also some for ore gen and block spawning. A new dev version will be released on the OTG Discord asap. If this problem remains, feel free to re-open this issue or create a new one, thanks!

**Closed as completed by PG85** 2019-08-21 23:05 UTC
Labels: Bug - Issue, Forge, Mod Compatibility, World/Biome/Terrain, Resource Spawning
