### ISSUE TITLE
Customstructure bo3 still spawning with cut offs

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#389] opened 2019-11-28 21:22 UTC
The structure in the below screenshot is made purely with 16x16 branches (created with OTGEdit) and is a normal bo3 customstructure with no 'checks' of any kind that would cause it to cancel. Prior to v8 these kinds of issues were not present.

![2019-11-28_21 17 17](https://user-images.githubusercontent.com/9453952/69832177-daf78a80-1224-11ea-9f98-a54d2a70f2f5.png)

Easy way to recreate the above: Use the seed `Creative` in Biome Bundle and go to the coords -105 64 475 and you will see the above (also confirmed by Irongrid in the discord). The bo3 in question is named hugearch.bo3 if you want to check it out.

**Comment by PG85** [comment] 2019-12-01 16:05
Confirmed, though I'm not sure whether this is a customstrucure missing its middle bit, or two customstructures that have both half-spawned. There's also a structure in between btw, the little pointy stone hill, patchyrocksmall, so this may be 3 customstructures? May be a problem with BO3 customstructures overriding each other or cancelling out each other's branches, may also be a problem with chunks not being populated properly (or multiple times).

Need to recreate this with a minimal test setup, Need to confirm: does the customstructure work properly in all other situations, does this only happen when multiple customstructures spawn next to / on top of each other? In which situations does this happen, what do they have in common?

Will require more testing and/or debugging.

**Comment by NLBlackEagle** [comment] 2019-12-20 22:42
I was under the impression this never happend to BBundle but apperantly it does. I am willing to bet all my savings this happens in the log:

![afbeelding](https://user-images.githubusercontent.com/4073584/71297111-6d053580-2382-11ea-9ba6-12a0075b3915.png)

The issue is the same as the one I just posted:
https://github.com/PG85/OpenTerrainGenerator/issues/406

**Comment by PG85** [comment] 2019-12-23 08:58
Same as #406 , closing this one.

**Comment by PG85** [comment] 2020-01-17 21:43
May not be the same after all. "minecraft engine attempted to populate two chunks at once" indicates cascading worldgen, blocks being spawned or checks being done in unloaded chunks. I'm not sure that's what's happening here (need confirmation for BB). I wonder if this might be related to "Double population prevented" or "Double population could not be prevented for chunk X0 Z0" messages in the logs. Need confirmation.

**Comment by PG85** [comment] 2020-01-17 21:47
*also need to know if the structures are cut off along chunk borders.

**Comment by PG85** [comment] 2020-02-09 07:47
Should hopefully be fixed with v9.0_r5

**Closed as completed by PG85** 2020-02-09 07:47 UTC
Labels: Bug - Issue, BO3's/BO4's, Support, Common
