### ISSUE TITLE
I updated the modpack "Life in a Village" today but it keeps crashing

### ISSUE THREAD

**Issue by Zerinna** [PG85/OpenTerrainGenerator#360] opened 2019-10-27 11:04 UTC
OTG Plugin or Mod

- [ x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
14.23.5.2831
#### Server/Client Log

[crash-2019-10-27_08.54.55-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3775688/crash-2019-10-27_08.54.55-server.txt)

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
I am playing "The Village Life" modpack of twitch 1.12.2 
#### Description

We are able to play for a little while but then often when someone brakes a block (seems to be random what block, 1 time was bricks another time sand) The server shuts down and I have to restart the server. 

Be able to play with no crashing.

**Comment by MCPitman** [comment] 2019-10-27 19:21
Duplicate of #361

**Comment by PG85** [comment] 2019-10-28 22:53
Thanks for reporting, closing as duplicate, please see original issue.

**Closed as completed by PG85** 2019-10-28 22:53 UTC
