### ISSUE TITLE
Crash: Crash with Mo' Villages

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#352] opened 2019-10-21 00:19 UTC
Forge: x.2847 for MC 1.12.2
OTG: V8 R8

https://paste.dimdev.org/lajecasiki.mccrash

Unsure which side is initiating the problem, advise redirection if necessary.

**Comment by PG85** [comment] 2019-10-28 21:30
Hey @DemonfangArun , thanks for reporting this. Currently some of OTG's vanilla structures inherit from MapGenStructure instead of their respective classes (MapGenVillage/MapGenScatteredFeature/StructureOceanMonument/WoodlandMansion), causing other mods to trip up when Forge events are fired. This will have to be fixed on the OTG side. As a quick fix, other mods could use MapGenStructure instead or do an instanceof check before casting to the class they need.

**Comment by Macleykun** [comment] 2021-04-03 09:49
Really glad that the issue is known and can be fixed from OTG's side! Mo' Villages seem to be abdoned and it's a great mod in my eyes.

If any testing has to be done, feel free to ask here as i would love to help out on this issue!

Thanks again to you two for time so far :)

**Comment by PG85** [comment] 2021-04-14 08:54
Hey @Macleykun , thanks for the feedback. This is still an issue for 1.12.2, we would have to reimplement the vanilla structures code in order to fix it. This is not something we intend to fix for 1.12.2 as we're focusing on 1.16, for 1.16 this won't be a problem. Mo' Villages could fix this by doing an instanceof check before doing any casts that throw an exception.

**Comment by Macleykun** [comment] 2021-04-14 11:16
Tottaly understand! The PM on forge can be dismissed!
Will see if i can find contact with the original developer. His code sadly isn't public, so have to look how i can resolve this.

I suggest this issue can be closed as it will be fixed on 1.16 and won't fix for 1.12.2. Thanks for the response!

**Closed as completed** 2021-04-21 16:34 UTC
Labels: Forge, Mod Compatibility, Resource Spawning, Bug - Crash

**Comment by Macleykun** [comment] 2021-04-24 14:11
The owner of MoVillages has fixed it, however he hasn't updated it to forge yet.
Communication is a bit difficult, so i'll share the jar he gave me.
[test3-MoVillages.jar.txt](https://github.com/PG85/OpenTerrainGenerator/files/6369748/test3-MoVillages.jar.txt)
Just remove the .txt part.
thx for closing the issue btw
