### ISSUE TITLE
[1.10.2] Client crash on world load (Dimensions)

### ISSUE THREAD

**Issue by ruyanve** [PG85/OpenTerrainGenerator#2] opened 2017-04-23 15:53 UTC
So I narrowed it down to Elemental Dimensions: https://minecraft.curseforge.com/projects/elemental-dimensions?gameCategorySlug=mc-mods&projectID=248539
Client locks up and doesn't even get to creating a crash log, so I had to copy from the client...
log: https://gist.github.com/ruyanve/c0a9cf806930e39e87918373e4a90bbc

**Comment by BakermanLP** [comment] 2017-04-23 18:42
That is at the moment the multi dimension thingy, that he is working on:
  Caused by: sun.reflect.generics.reflectiveObjects.**NotImplementedException**

He is working on that.

**Comment by Beanius** [comment] 2017-04-23 19:47
Latest update v15 fixed my Harvest festival load up issue, seems to have been the same error you got there B) Test that version out 👍

**Comment by PG85** [comment] 2017-04-27 12:32
Thanks for the report and the assistance guys, please check out v15 or v16 from https://minecraft.curseforge.com/projects/open-terrain-generator/files and tell me if that fixes the issue.

**Comment by PG85** [comment] 2017-04-27 14:18
Closing for now, feel free to reopen if the issue is not solved with v15 or v16

**Closed as completed by PG85** 2017-04-27 14:18 UTC

**Comment by ruyanve** [comment] 2017-04-27 16:25
Will do, I'm on the road for a couple of days so I can't really test. 
Thanks mate!
