### ISSUE TITLE
Otg 1.17.1 0.0.20 doesn't generate mobs.

### ISSUE THREAD

**Issue by NearBeauty** [PG85/OpenTerrainGenerator#883] opened 2021-09-27 21:01 UTC
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.17.1 0.0.20

#### Forge or Spigot Versions
Paper version git-Paper-264 (MC: 1.17.1)

#### Description
In the whole overworld no mob is generated, only villagers.

**Comment by FrankTCA** [comment] 2021-09-27 21:06
Is this because we haven't added in mob spawning for the 1.17 branch yet or is there something going wrong?

**Comment by NearBeauty** [comment] 2021-10-03 16:13
> Is this because we haven't added in mob spawning for the 1.17 branch yet or is there something going wrong?
I think that in general the support for mob generation has not been added, I'm not sure.

**Comment by authvin** [comment] 2021-10-03 16:30
Three questions before I start looking deeper at this
- What preset are you running?
- How is mob spawning configured in that preset?
- Does the preset as configured spawn mobs in 1.16?

**Comment by NearBeauty** [comment] 2021-10-03 16:44
> Three questions before I start looking deeper at this
> 
> * What preset are you running?
> * How is mob spawning configured in that preset?
> * Does the preset as configured spawn mobs in 1.16?

WildLands, in the 1.16.5 it worked, but now in the latest release for 1.17.1 it doesn't works.

**Comment by NearBeauty** [comment] 2021-10-03 18:16
And also I'm using all the default settings, I didn't change nothing

**Comment by FrankTCA** [comment] 2021-10-04 02:02
It appears to me that OTGNoiseChunkGenerator.addMobs() is non-existent. Maybe it was left out for a reason?

**Comment by authvin** [comment] 2021-10-04 08:09
that method is now called spawnOriginalMobs, and is implemented the same way as it was in 1.16

**Comment by PG85** [comment] 2021-10-04 08:19
Note that mob spawning happens at two moments, once at the end of decoration (animals), and on tick (monsters). In both cases all we should be doing is registering mob spawn lists to biomes, the rest is mc flow. Our spawnOriginalMobs should basically do the same as vanilla's, the only time we do any explicit spawning of mobs is for Entity(). Would be good to check if mobs are being registered to biomes properly. Not sure if /otg biome -m properly reports that yet (it used to just report biomeconfig spawn list)?

**Comment by authvin** [comment] 2021-10-04 16:36
Fixed in 1.17-0.0.21 by https://github.com/PG85/OpenTerrainGenerator/commit/2a77b3fa35bef7bfaf9c5b5fe4f47c10c3cd8839

Root cause was paper's resource locations changing format from "minecraft:entity/chicken" to "minecraft:entity.minecraft.chicken"

**Closed as completed by authvin** 2021-10-04 16:36 UTC
Labels: Bug - Issue, Mob/Entity Spawning

**Comment by authvin** [comment] 2021-10-04 16:44
[dev build.zip](https://github.com/PG85/OpenTerrainGenerator/files/7279815/dev.build.zip)

Here's a build with these specific fixes. Note that this is an unoffocial build, and not the full 1.17.1-0.0.21 build.

**Comment by NearBeauty** [comment] 2021-10-04 19:16
> [dev build.zip](https://github.com/PG85/OpenTerrainGenerator/files/7279815/dev.build.zip)
> 
> Here's a build with these specific fixes. Note that this is an unoffocial build, and not the full 1.17.1-0.0.21 build.

Thanks, I'll test that build in some hours 😄.

**Comment by NearBeauty** [comment] 2021-10-05 05:14
Yes, fixed, thank you.
