### ISSUE TITLE
Upgrading from v6 to v8 crashes if there is a biome ID conflict

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#367] opened 2019-11-04 21:53 UTC
If a world created in v6 had a biome ID conflict, OTG just silently allowed it to happen whereas if you upgrade that world to v8 it will try to use the same IDs and crash with the following error:
https://pastebin.com/nKJTn5Ej

**Comment by PG85** [comment] 2019-11-05 12:38
Thank for reporting, do you have an example world or an easy way to create one?

**Comment by cheshyrp** [comment] 2019-11-09 15:56
There is an easy reproduction if you have the Twitch launcher. Download the Roguelike Dungeons and Adventures modpack, create a world, then update OTG and you should see the error.

**Comment by PG85** [comment] 2019-11-26 22:05
Would be good to at least log a proper error, if fixing it properly takes too much time.

**Comment by PG85** [comment] 2020-01-20 20:59
Logging a proper error, unfortunately I don't think I can remap biome id's for existing worlds so won't fix.

**Comment by PG85** [comment] 2020-01-20 21:03
*Hm ok nm, if I understand correctly, I wouldn't have to remap biome id's for the world, but would just have to make v8 imitate the way v6 handled biome id's for conflicted biomes. If v6 detected a conflict, did it just ignore the biome completely, or did it get a different id than defined in the worldconfig?

**Comment by PG85** [comment] 2020-01-24 21:19
As this is a bit of a pita to confirm (have to dig into v6 code) and may not affect many people, will put this into support milestone for now. If someone is actually stuck with this problem and can reproduce it, I'll take another look. I'll need some logs that show otg v6 registering the conflicted biomes at world load (raise log level in OTG.ini if necessary), so I can see what id's the biomes are being mapped to.

**Comment by PG85** [comment] 2020-01-24 22:34
Took a quick look with the Twitch launcher and Roguelike Dungeons and Adventures modpack, unfortunately it doesn't log any info when registering biomes on world load. I think that version has the bug where the log messages only appear in the debug.log, which the twitch launcher doesn't create.

**Comment by authvin** [comment] 2020-01-25 12:27
[debug otg v6.log](https://github.com/PG85/OpenTerrainGenerator/files/4112000/debug.otg.v6.log)

This is a trace-level debug.log from running OTG v6, Dregora v1.5.6, and Twillight Forest 3.10.1013. Heavily edited to be more easily readable. I'm not sure if I can get more detailed logs than this.

**Comment by authvin** [comment] 2020-01-25 12:54
[debug OTG v6 BB.log](https://github.com/PG85/OpenTerrainGenerator/files/4112028/debug.OTG.v6.BB.log)

Here's a similar log running Biome Bundle instead of Dregora. Slimmed down again, even more than the first one.

Got a new one because I noticed the Dregora world didn't crash when loading it in v8, whereas the BB one did.

**Comment by PG85** [comment] 2020-01-25 15:27
Very nice, thanks! Now all I need is a log of the crash in v8, to see which biomes its complaining about. Can also upload the world save, ofc then I'd need all the mods too.

**Comment by authvin** [comment] 2020-01-25 15:32
[crash-2020-01-25_16.29.46-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4112186/crash-2020-01-25_16.29.46-server.txt)

Here's the crash, it crashes when colliding with the first one so it's just the name of one of the biomes. Any other files you'd like?

**Comment by PG85** [comment] 2020-01-26 14:34
should be fixed for v9.0_r3, to be released on the otg discord asap, thanks for reporting!

**Closed as completed by PG85** 2020-01-26 14:34 UTC
Labels: Mod Compatibility, World/Biome/Terrain, Common, Bug - Crash
