### ISSUE TITLE
OTG v9_r7 crashes when using Yung's Better Caves mod.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [PG85/OpenTerrainGenerator#443] opened 2020-02-22 19:03 UTC
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
-[ x ] 1.12.2_V9_r7
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[Forge 1.12.2-14.23.5.2846 ]

#### Server/Client Log
https://pastebin.com/vL7KAra0

#### What other plugins are you running?

	| State  | ID                   | Version               | Source                                          | Signature                                |
	|:------ |:-------------------- |:--------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                  | 9.42                  | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | forge                | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | ivtoolkit            | 1.3.3-1.12            | minecraft.jar                                   | None                                     |
	| LCHIJA | otgcore              | 1.12.2 - v9.0_r7      | minecraft.jar                                   | None                                     |
	| LCHIJA | actuallyadditions    | 1.12.2-r151           | ActuallyAdditions-1.12.2-r151-2.jar             | None                                     |
	| LCHIJA | ambientsounds        | 3.0                   | AmbientSounds_v3.0.9_mc1.12.2.jar               | None                                     |
	| LCHIJA | jei                  | 4.15.0.293            | jei_1.12.2-4.15.0.293.jar                       | None                                     |
	| LCHIJA | appleskin            | 1.0.9                 | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LCHIJA | ebwizardry           | 4.2.9                 | ElectroblobsWizardry-4.2.9-MC1.12.2.jar         | None                                     |
	| LCHIJA | arcane_essentials    | 1.0                   | Arcane+Essentials-1.0.0-alpha-5.jar             | None                                     |
	| LCHIJA | betteranimals        | 5.3.0                 | betteranimals-1.12.2-5.3.0.jar                  | None                                     |
	| LCHIJA | quark                | r1.6-177              | Quark-r1.6-177.jar                              | None                                     |
	| LCHIJA | autoreglib           | 1.3-32                | AutoRegLib-1.3-32.jar                           | None                                     |
	| LCHIJA | betteradvancements   | 0.1.0.77              | BetterAdvancements-1.12.2-0.1.0.77.jar          | None                                     |
	| LCHIJA | betteranimalsplus    | 8.2.0                 | betteranimalsplus-1.12.2-8.2.0.jar              | None                                     |
	| LCHIJA | bettercaves          | 1.12.2                | bettercaves-1.12.2-1.6.0.jar                    | None                                     |
	| LCHIJA | betternether         | 0.1.8.6               | betternether-0.1.8.6.jar                        | None                                     |
	| LCHIJA | openterraingenerator | v9.0_r7               | OpenTerrainGenerator-1.12.2_-_v9.0_r7.jar       | None                                     |
	| LCHIJA | biomebundle          | 5.1                   | Biome_Bundle-1.12.2-v6.1.jar                    | None                                     |
	| LCHIJA | butterflies          | 1.12.2-1.0.2          | butterflies-1.12.2-1.0.2.jar                    | None                                     |
	| LCHIJA | carryon              | 1.12.3                | CarryOn+MC1.12.2+v1.12.3.jar                    | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | ceramics             | 1.12-1.3.7            | Ceramics-1.12-1.3.7.jar                         | None                                     |
	| LCHIJA | charm                | 1.12.2-1.3.6          | Charm-1.12.2-1.3.6.jar                          | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux         | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore             | 4.6.3                 | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
	| LCHIJA | cofhworld            | 1.3.1                 | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | comforts             | 1.4.1.3               | comforts-1.12.2-1.4.1.3.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | coralreef            | 2.0                   | CoralReef-2.5-1.12.2.jar                        | None                                     |
	| LCHIJA | chickenshedcontinued | 1.0                   | CSC-1.12-1.0.jar                                | None                                     |
	| LCHIJA | despeggshatch        | 1.1                   | despeggshatch_1.12-1.1.jar                      | None                                     |
	| LCHIJA | dregora              | 1.0                   | Dregora-1.12.2-v1.64+Ocean+.jar                 | None                                     |
	| LCHIJA | orelib               | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.0.2               | DynamicSurroundings-1.12.2-3.6.0.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | enchdesc             | 1.1.19                | EnchantmentDescriptions-1.12.2-1.1.19.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ethicalarrows        | 1.0                   | EthicalArrows+-+1.0.jar                         | None                                     |
	| LCHIJA | fastleafdecay        | v14                   | FastLeafDecay-v14.jar                           | None                                     |
	| LCHIJA | ferdinandsflowers    | 1.10.4.1              | Ferdinand's+Flowers-1.12.x-1.10.4.1.jar         | None                                     |
	| LCHIJA | cfm                  | 6.3.1                 | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCHIJA | infinitetippedarrows | 1.0                   | InfiniteTippedArrows.jar                        | None                                     |
	| LCHIJA | inventorytweaks      | 1.64+dev.150.7168e7a  | InventoryTweaks-1.64+dev.150.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.9          | journeymap-1.12.2-5.5.9.jar                     | None                                     |
	| LCHIJA | jaff                 | 1.7_for_1.12          | JustAFewFish-1.7_for_1.12.jar                   | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| LCHIJA | minicoal             | 1.0                   | minicoal-1.12.2-1.0.jar                         | None                                     |
	| LCHIJA | patchouli            | 1.0-20                | Patchouli-1.0-20.jar                            | None                                     |
	| LCHIJA | pathundergates       | 1.12.2-2.0.0-release  | pathundergates-1.12.2-2.0.0-release.jar         | None                                     |
	| LCHIJA | randomtweaks         | 1.12.2-2.7.1.0        | randomtweaks-1.12.2-2.7.1.0.jar                 | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | reap                 | 1.5.3                 | reap-1.5.3.jar                                  | None                                     |
	| LCHIJA | reccomplex           | 1.4.8.2               | RecurrentComplex-1.4.8.2.jar                    | None                                     |
	| LCHIJA | savemystronghold     | 1.12.2-1.0.0          | savemystronghold-1.12.2-1.0.0.jar               | None                                     |
	| LCHIJA | t3s4ebw              | 1.0                   | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar    | None                                     |
	| LCHIJA | silentlib            | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar                 | None                                     |
	| LCHIJA | silentgear           | 0.6.5                 | SilentGear-1.12.2-0.6.7+76.jar                  | None                                     |
	| LCHIJA | silentgems           | 2.8.18                | SilentsGems-1.12.2-2.8.22+327.jar               | None                                     |
	| LCHIJA | spartanshields       | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                 | None                                     |
	| LCHIJA | theoneprobe          | 1.4.28                | theoneprobe-1.12-1.4.28.jar                     | None                                     |
	| LCHIJA | thermalfoundation    | 2.6.3                 | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion     | 5.5.4                 | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics      | 2.5.5                 | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | undergroundbiomes    | 1.3.7                 | UndergroundBiomesConstructs-1.12-1.3.7.jar      | None                                     |
	| LCHIJA | unenchanting         | 1.1.1                 | unenchanting-1.1.1.jar                          | None                                     |
	| LCHIJA | vanillavistas        | 1.0                   | Vanilla_Vistas+1.1.jar                          | None                                     |
	| LCHIJA | vanillafoodpantry    | 4.3.1                 | vanillafoodpantry-mc1.12.2-4.3.1.jar            | None                                     |

#### Description
Crashes when starting a new world.

Can you provide a Minimal, Reproducible Example? 

Start a new world with OTG_v9_r7 and Yungs Better Caves

**Comment by yungnickyoung** [comment] 2020-03-03 20:34
The issue is here:

https://github.com/PG85/OpenTerrainGenerator/blob/174ed59b36bff94765a9853d36a91e5f356456ea/platforms/forge/src/main/java/com/pg85/otg/forge/world/ForgeWorld.java#L151

Instead this should be something like:
`this.cavesGen = net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(new MapGenCaves(), net.minecraftforge.event.terraingen.InitMapGenEvent.EventType.CAVE);`

My mod checks the original gen to avoid weird scenarios like processing the same chunk twice. The original gen needs to be nonnull for this to work, or else a `NullPointerException `will be thrown. In general it's not good practice to set the original gen to null. IMO it should be left untouched, and only overridden with valid `MapGenBase` children.

**Comment by PG85** [comment] 2020-03-03 20:42
Thanks for looking into this @yungnickyoung. Even though OTG won't actually ever use the vanilla cavegen, I'll insert a new instance instead of null, in order to emulate normal behaviour. Will be fixed for v9_r8.

**Closed as completed by PG85** 2020-03-03 20:42 UTC
Labels: Mod Compatibility, World/Biome/Terrain, Bug - Crash

**Comment by yungnickyoung** [comment] 2020-03-03 20:44
Great. Thanks for the quick response!
