### ISSUE TITLE
Issue - Sea Level Only Partially functioning MC-1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PG85/OpenTerrainGenerator#6] opened 2017-04-23 18:11 UTC
After Setting the Sea Level to 78 from 50 It only filled empty water blocks one black high in empty spots so indeed anything that was below 78 has water it didn't mean filled . So my ocean has giant holes as seen here. 
![2017-04-23_13 08 39](https://cloud.githubusercontent.com/assets/10351221/25316092/547eb3b0-2826-11e7-801a-2e844823bfd4.png)

**Comment by P3rf3ctXZer0** [comment] 2017-04-23 18:11
help @.@

**Comment by PG85** [comment] 2017-04-27 12:26
Hey, please create a post on /r/openterraingen or /r/biomebundle to get advice from experienced OTG content creators.

**Comment by PG85** [comment] 2017-04-27 14:16
This is most likely not a bug but a worldconfig/biomeconfig settings issue, closing it now.

**Closed as completed by PG85** 2017-04-27 14:16 UTC
