### ISSUE TITLE
Bug: Mekanism + OTG Nether Portal not working

### ISSUE THREAD

**Issue by dansecan25** [PG85/OpenTerrainGenerator#264] opened 2019-06-14 21:13 UTC
I have around 39 other mods installed(AE2, better animals+, code chicken, coroutil, corpse, craft tweaker, hwyla, iblis, ice and fire, ichun util, jei, large fluid tank, llibrary, MCA, mekanism, mekanism generators, mekanism tools, mob dismemberment, my chunk loader, NEI, optifine, radixcore, resynth, u team core, useful back packs, voxel map and weather 2) and the nether worked perfectly, but when i intsalled biome bundle and OTG, when I activated the nether portal, instead of the portal blocks, a purple and black block appeared(as if there was no texture for it) and when entering them, the portal noise was still there, but it wouldn't teleport me to the nether and after a while the portal disappears.

**Comment by dansecan25** [comment] 2019-06-14 21:46
![Screen Shot 2019-06-14 at 3 44 59 PM](https://user-images.githubusercontent.com/51306347/59539719-8dc46e00-8ebb-11e9-9093-f63ffaa91421.png)

**Comment by dansecan25** [comment] 2019-06-14 21:47
Anyway, only the nether is not working, I searched and used a end portal and works perfectly fine

**Comment by PG85** [comment] 2019-06-15 13:26
Hey, thanks for reporting. Which version of OTG are you using? I've not seen this problem before so it may be related to a specific mod combination. Please remove as many mods as possible and see if you can still reproduce it, thanks!

**Comment by dansecan25** [comment] 2019-06-15 23:02
The file says OpenTerrainGenerator-1.12.2+-+V6. I am going to start removing to see if it still happens.

**Comment by dansecan25** [comment] 2019-06-15 23:21
I took out every main mod except for the corpse mod, and left the bime bundle and otg with llibrary, ichunutil, coroutil, codechicken lib, radix core, optifine, u team core, and nei and jei, and the nether worked, so now I will star adding mods one by one.

**Comment by dansecan25** [comment] 2019-06-15 23:56
So i started adding one by one the mods, and testing the nether, when I inserted the mekanism, mekanism tools, and mekanism generators mods, and tried to open the nether, the problem appeared again, so I took every main mod out again and left the mekanism mods in, and the problem continued

**Comment by PG85** [comment] 2019-07-30 19:32
Sorry for the late response and thanks for tracking this down. I've made a lot of changes related to dimensions and portals for v7, could you grab the latest build from the OTG Discord #OpenTerrainGen's otg-dev channel and see if that fixes the problem for you? Thanks!

**Comment by dansecan25** [comment] 2019-07-31 16:45
Sure, np, as soon as I return to my computer, I will try it

**Comment by dansecan25** [comment] 2019-07-31 21:00
Still doesn't work, and definitely is when I install the mekanism mods.

**Comment by dansecan25** [comment] 2019-07-31 21:01
well, it happens when I install it, however, if I activate the nether portal before installing them, it works always if I don't destroy it and turn it on again.

**Comment by PG85** [comment] 2019-08-05 09:05
Ok, thanks for testing, will take a look at this for v8, if time permits.

**Comment by PG85** [comment] 2019-08-22 08:50
@dansecan25, btw, have you also checked on the Mekanism side if there are similar issues with other mods? Also, what dimension features does Mekanism itself have?

**Comment by PG85** [comment] 2019-08-22 08:51
Will move this out of the v8 milestone, can still include it in the release if it's solved in time, otherwise can include it in a smaller update later.

**Comment by dansecan25** [comment] 2019-08-22 20:44
I haven’t tried it, I can try it this weekend, i haven’t fully explored the mekanism mod for the moment, as far as I know it doesn’t feature any dimension, but it has a teleporter, I don’t know if it counts as a dimension, I haven’t used it

**Comment by PG85** [comment] 2019-11-26 21:30
Needs to be tested.

**Comment by PG85** [comment] 2020-01-18 08:49
Closing this because it's old, lots of things have been fixed for dimensions. Feel free to reopen or create a new issue if this problem still occurs with newer versions of OTG (8.3+), thanks!

**Closed as completed by PG85** 2020-01-18 08:49 UTC
Labels: Bug - Issue, Forge, Mod Compatibility, Dimensions
