### ISSUE TITLE
pregen will not stop

### ISSUE THREAD

**Issue by halfpastfouram** [PG85/OpenTerrainGenerator#402] opened 2019-12-17 20:11 UTC
---
name: Bug report
about: I cannot stop the pregen process.

---
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [x] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
I'm using forge-1.12.2-14.23.5.2838-universal.jar.

#### Server/Client Log
[server.log](https://github.com/PG85/OpenTerrainGenerator/files/3975240/server.log)

#### What other plugins are you running?
AtomicStryker's Infernal Mobs (by AtomicStryker)
Waystones (by BlayTheNinth)
IvToolkit (by Ivorforce)
Quality Tools (by Tmtravlr)
The Disenchanter Mod (by eusunt)
Random Loot Mod (by milomaz1)
DimensionalDoors (by DimensionalDevelopment)
Reliquary v1.3 (by P3pp3rF1y)
Open Terrain Generator (OTG) (by team_otg)
Scaling Health (by SilentChaos512)
NetherEx (by LogicTechCorp)
No Recipe Book (by Seneschal_Luwin)
Placeable Items (by Ferdz)
VanillaTweaks (by StrikerRocker)
Bountiful (by ejektaflex)
Dungeon Tactics (by PegBeard)
Tropicraft (by Cojomax99)
ItemPhysic Lite (by CreativeMD)
V-Tweaks (by oitsjustjose)
VanillaFix (by Runemoro)
Improved Backpacks (by DreenDex)
AutoRegLib (by Vazkii_)
CraftTweaker (by Jaredlll08)
BiblioCraft (by JDSinclair)
Progressive Bosses (by InsaneGames_)
Controlling (by Jaredlll08)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Enchantment Descriptions (by Darkhax)
Extra Spells (Electroblob's Wizardry) (by meldexun)
ForgeEndertech (by EnderLanky)
Cyclic (by Lothrazar)
Heroic Armory (by skeddles)
Aether: Lost Content (by KingPhygieBoo)
Creeper Confetti (by SR2610)
Biome Bundle (by mc_pitman)
Mowzie's Mobs (by BobMowzie)
Notes (by ChaosTheDude)
FTB Utilities (by FTB)
Iron Backpacks (by gr8pefish)
Just Enough Items (JEI) (by mezz)
Living Enchantment (by Clownvin)
Tomb Many Graves 2 (by M4thG33k)
Land Manager (by bright_spark)
Baubles (by azanor)
Aroma1997Core (by Aroma1997)
Rough Tweaks (by Lellson)
Rustic (by mangoose3039)
FoamFix for Minecraft (by asiekierka)
FTB Library (by FTB)
Akashic Tome (by Vazkii_)
Skewers (by casadis)
Inventory Pets (by Purplicious_Cow)
Nature's Compass (by ChaosTheDude)
Simple Storage Network (by Lothrazar)
Roguelike Dungeons (by Greymerk)
Cyclops Core (by kroeser)
TombManyGraves 2 API (by M4thG33k)
CplPibald's Tweaks (by CplPibald)
TombManyPlugins - Cosmetic Armor Reworked (by M4thG33k)
Neat (by Vazkii_)
Signpost (by Gollorum)
Terracart Reloaded (by kreezxil)
Just Enough Resources (JER) (by Way2muchnoise)
Shadowfacts' Forgelin (by shadowfactsmc)
Potion Core (by Tmtravlr)
Aether Continuation (by Raptor4694)
Extra Alchemy (by zabi94)
Portable Crafting (by gr8pefish)
LimeLib (by KidsDontPlay)
Cosmetic Armor Reworked (by ZLainSama)
Sound Filters (by Tmtravlr)
Doomlike Dungeons (by BlackJar72)
Charm (by svenhjol)
MegaLoot (by Winter_Grave)
Chest Transporter (by CubeX2)
Pyramid Plunder (by Laton95)
Spice of Life: Carrot Edition (by LordCazsius)
Silent Lib (by SilentChaos512)
Random Things (by lumien231)
OreLib (by OreCruncher)
The Aether (by GildedGames)
ConnectedTexturesMod (by tterrag1098)
Jack-O'-Launcher (by ochotonida)
Enhanced Armaments (by jannesoon)
AI Improvements (by DarkGuardsman)
Bloodmoon (by lumien231)
Ore Excavation (by Funwayguy)
Chisel (by tterrag1098)
LibraryEx (by LogicTechCorp)
Quark (by Vazkii_)
Doggy Talents (by percivalalb)
Totemic (by ljfa)
SwingThroughGrass (by exidex)
Spawn Temple (by iastre)
Custom Main Menu (by lumien231)
Chance Cubes (by turkey2349)
Rats (by alex1the1666)
DefaultSettings (by PT400C)
Cavern II (by _kegare)
EZStorage 2 (by zero__fall)
Prefab (by WuestMan)
Inventory Tweaks (by Kobata)
AppleSkin (by squeek502)
Resource Loader (by lumien231)
Bigger Packets Please (by ElNounch65668)
Aquaculture (by Shadowclaimer)
Better Questing - Quest Book (by Drethic)
Unique Crops (by bafomdad)
Subterranean Switcheroo (by ArloTheEpic)
Recurrent Complex (by Ivorforce)
Engineers Workshop Reborn (by modmuss50)
Nomadic Tents (by skyjay1)
Fast Leaf Decay (by Olafskii)
Ordinary Coins (by flametaichou)
World Primer (by masa_)
Mouse Tweaks (by YaLTeR97)
The Twilight Forest (by Benimatic)
Aroma1997s Dimensional World (by Aroma1997)
BetterFps (by Guichaguri)
Mystical Agriculture (by BlakeBr0)
Cucumber Library (by BlakeBr0)
LLibrary (by iLexiconn)
Electroblob's Wizardry (by electroblob)
Customized Dungeon Loot (by XxRexRaptorxX)
Login Shield (by Glasspelican)
Level Up! Reloaded (by BeetoGuy)
Better Questing (by Funwayguy)
Better Questing - Standard Expansion (by Funwayguy)
Project: Vibrant Journeys (by solis_nova123)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
Straw Golem (by fradige9512794)
Dynamic Surroundings (by OreCruncher)
[ANGRY PIXEL] The Betweenlands (by oily_oli)
JourneyMap (by techbrew)
Hwyla (by TehNut)
GottschCore (by gottsch)
Phosphor (by jellysquid_)
FTB Utilities: Backups (by LatvianModder)
Extra Utilities (by RWTema)
Comforts (by theillusivec4)
ViesCraft - Airships! (by Viesis_Gaming)
The Beneath (by Shinoow)
Colossal Chests (by kroeser)
AppleCore (by squeek502)
The Eight Fabled Blades (by shelterrin)
Better Advancements (by Way2muchnoise)
InGame Info XML (by Lunatrius)
LunatriusCore (by Lunatrius)
Reborn Core (by modmuss50)

#### Description
The pregen process was set to 256 but I updated it to 512 before it got there. The server later crashed due to not enough memory but after giving it more memory it worked again. Later I saw the pregen process exceeded the 512 radius and it is currently at 611.

Doing `/otg pregen 0` does not stop the process.

**Comment by halfpastfouram** [comment] 2019-12-17 20:23
I've tested with V8 but then it just crashes: 
[crash-2019-12-17_21.21.25-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3975296/crash-2019-12-17_21.21.25-server.txt)

**Comment by MCPitman** [comment] 2019-12-17 22:03
Based on your reddit post here: https://www.reddit.com/r/biomebundle/comments/ec0hw3/otg_pregen_will_not_stop/

The process is working as intended, I've answered there. Closing this as it doesn't appear there's a problem.

**Closed as completed by MCPitman** 2019-12-17 22:03 UTC

**Comment by halfpastfouram** [comment] 2019-12-17 22:13
I'm sorry but there is nothing for you to base that on. I've been running the server for hours and it's been generating chunks for well over 100 outside the configured radius. It's still happening.
