### ISSUE TITLE
Biome group placement is broken in 'Normal' mode

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#424] opened 2020-01-26 13:27 UTC
Can add more detail if needed but there are two main issues:

1) The first biome group listed of the largest size in the worldconfig has will place at 0,0 even if its rarity is 1 (and then never place again). Meaning that players tend to spawn in the same biome group regardless of seed and rarity.

2) Biome group rarity does not seem to work as intended as it places the same biome groups in the same places regardless of seed, even if the biome groups have a chance to 'fail' their rarity test.

**Comment by Darsenia** [comment] 2020-01-30 19:02
Yes, I can confirm it too.More, the player spawns mostly in the first biome group in the list, if every group has the same size and rarity, even if this group has low rarity.For some reson in v6 spawn seems to be a bit more random with groups with the same size.In v8 I almost every time spawn in the very first group.

**Comment by PG85** [comment] 2020-07-18 13:26
Fixed by @SuperCoder7979  for 1.12.2 v9_r9.

**Closed as completed by PG85** 2020-07-18 13:26 UTC
Labels: Bug - Issue, World/Biome/Terrain, Common
