### ISSUE TITLE
Zombie Pigmen from OTG portals / Portals disappear on block update

### ISSUE THREAD

**Issue by Fnige** [PG85/OpenTerrainGenerator#452] opened 2020-03-28 10:18 UTC
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2 v8.3

#### Forge or Spigot Versions
14.23.5.2847

#### What other plugins are you running?
FTB Builders Paradise 1.6.0
Decocraft 2.6.3 (PTRLib 1.0.4)
Extra Utilities 2 1.9.9

#### Description
What is happening?
Zombie Pigmen can and will spawn from the OTG portals
How to reproduce: Make a OTG portal, then wait

What did you expect to happen?
Well, I expected for zombie pigmen to not spawn from the portal

**Comment by MCPitman** [comment] 2020-03-28 10:42
Just tested this with only OTG installed and I can't reproduce it, must be caused by a mod conflict. Will need more information about what mod is causing this to track it down.

**Comment by PG85** [comment] 2020-07-18 12:20
Hey @SlimyPython , this should hopefully be fixed for v9. Please try the latest dev version from the OTG Discord at https://discord.gg/UXzdVTH. If the problem still occurs, feel free to reopen this issue, thanks!

**Comment by PG85** [comment] 2020-07-19 10:27
Confirmed not fixed. 

Zombie pigmen spawning out of portals should be fixed, otg is not intercepting the vanilla behaviour atm.
Portals also shouldn't disappear when neighbouring blocks trigger a block update, otg also isn't intercepting that vanilla behaviour atm.

**Comment by PG85** [comment] 2020-08-01 02:35
Fixed for v9_r10.

**Closed as completed by PG85** 2020-08-01 02:35 UTC
Labels: Bug - Issue, Forge, Dimensions
