### ISSUE TITLE
Bug: Spigot stacking villages

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#383] opened 2019-11-22 16:37 UTC
#### OTG Plugin or Mod
- [X] OTG Plugin for Spigot

#### OTG Version
- [X] 1.12.2_v8.2

#### Forge or Spigot Versions
Spigot 1.12.2 R0.1-SNAPSHOT

#### What other plugins are you running?
EssentialsX-2.17.1.0

#### Description
Village spawns two times on top of each other where it should only spawn once.
Image: https://cdn.discordapp.com/attachments/307111022257373185/647472058837499905/unknown.png

Location is at 1289 110 -1509 this issue however does not seem to happen at 1770 108 -2717

I've traveled over the world and the issue only seems to happen here with seed: Dregora
Given these factors it happens extremely rarely but might still be worth checking into.

#### Simplified world:
https://dregora.com/wp-content/uploads/2019/11/DoubleVillage.zip

**Comment by PG85** [comment] 2019-11-26 20:32
Thanks for reporting this, I haven't seen this myself but let's see if more users report this. Since it appears to be uncommon and hard to reproduce, will move to backlog for now (until more users report it).

**Comment by MCPitman** [comment] 2019-11-26 20:34
I vaguely remember seeing this happen when you log out of a world, delete region files and then go back in and regenerate them.

**Comment by TheForgottenKing** [comment] 2020-02-22 19:40
I've had this issue happen once on 1.12.2 spigot as well

**Comment by PG85** [comment] 2020-12-05 21:16
Villages will be completely reimplemented for 1.16, so shouldn't have this issue. We won't be fixing this for 1.12.2 anymore (unless someone really wants to take a look?). Thanks for reporting!

**Closed as completed by PG85** 2020-12-05 21:16 UTC
Labels: Bug - Issue, Resource Spawning, Common
