### ISSUE TITLE
[1.12.2]Stuck loading world with biome bundle

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#83] opened 2017-11-27 23:33 UTC
MC 1.12.2
Forge 1.12.2 - 14.23.1.2556
Foamfix-0.8.1-1.12-anarchy
OptiFine_1.12.2_HD_U_C6
6GB RAM Allocated

Keep getting this spammed in my log: https://pastebin.com/mc4XwgVG
Full log: https://pastebin.com/Q153Dnun
Crash report after force closing the game: https://pastebin.com/7YLbkAKc

**Comment by ghost** [comment] 2017-11-28 20:16
Same issue; did some testing (1 by 1 mod disabling).
If Farseek (required for Streams) is enabled, this error is triggered.

**Comment by delvr** [comment] 2017-12-03 03:17
Farseek/Streams dev here - this seems to be a duplicate of #80 and is now fixed on the Farseek side in delvr/Farseek#35.

**Comment by PG85** [comment] 2017-12-23 23:13
Thanks for reporting and thanks for the update @delvr :).

**Closed as completed by PG85** 2017-12-23 23:13 UTC
