### ISSUE TITLE
Sapling Listener / Growth Server Crash 

### ISSUE THREAD

**Issue by GGriddy** [PG85/OpenTerrainGenerator#361] opened 2019-10-27 16:09 UTC
#### OTG Plugin or Mod

- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions

Forge [14.23.5.2831]

#### Server/Client Log

Complete console log: [link](https://paste.bombsite.be/opakazobon)
Latest crash report: [link](https://hastebin.com/agovoqejel)

#### What other plugins are you running?

Life in the Village 1.15 Modpack
List of mods included in the modpack [here](https://www.curseforge.com/minecraft/modpacks/life-in-the-village/relations/dependencies).

#### Description

The Server crashes unexpectedly, without prior warning or any event that seems to make it crash.

From the crash report, it seems to be caused by sapling growth linked to OTG.

**Comment by authvin** [comment] 2019-10-27 17:54
I've managed to narrow down the issue to only happening when a sapling that has a 2x2 variant, i.e. a jungle, dark oak or spruce sapling, tries to grow when next to a chunk border towards negative x or z

**Comment by BiomeBundle** [comment] 2019-10-27 17:55
So this is consistently reproducible with only OTG installed by planting saplings on chunk borders, correct?

**Comment by GGriddy** [comment] 2019-10-27 18:00
From what I've experienced, yes. One of my worlds does not have the Biome Bundle generation and the crash still happens, although the mod is indeed installed.

**Comment by authvin** [comment] 2019-10-27 18:05
I was testing with a default preset, only mods installed were Biomes o Plenty and the one probe. Was using bone meal to trigger the growth

**Comment by Zerinna** [comment] 2019-10-27 23:49
ok so how do we fix this?

**Comment by MCPitman** [comment] 2019-10-27 23:50
you wait for the next OTG patch

**Comment by Zerinna** [comment] 2019-10-28 00:05
+


> you wait for the next OTG patch

Is  there a way to turn off 2x2 sapling generation in the config and restart the map?

**Comment by authvin** [comment] 2019-10-28 18:06
So I did some more testing, and it's more complicated than I thought. Feel free to skip to the end.

Take Chunk A and Chunk B. The two chunks are next to each other, B is west of A. Assume neither chunk has been interacted with since restart.

I still have only Biomes o Plenty and The One Probe installed, running a default OTG preset. Running in Forge single player, with version 1.12.2_v8_r6_Josh4.

- Test 1: If I place a sapling in Chunk A but not on the border and grow it, I can then place a sapling in Chunk B on the border to Chunk A and grow it with bonemeal. I can then place a sapling in Chunk A on the border to Chunk B and grow it the same way. No crash.
- Test 2: If I place a jungle sapling in the middle of Chunk A and then place a sapling in Chunk A on the border to Chunk B, the sapling won't grow with bonemeal. No crash.
- Test 3: If I grow a sapling in A and in B and then place a sapling down on the border, it will eventually grow. No bonemeal used. I've turned random tick speed up to 300 to speed this process up. No crash.
- Test 4: If I grow a sapling in A but not in B and place a sapling down on the border to B, then wait for the sapling to grow on its own, the server does eventually crash. I'm still on random tick speed 300 here.
- Test 5: Place a sapling down on any border between two chunks that haven't been interacted with at all. If the border is on the east, west or north side of the chunk, the game will soon crash. If it's on the north side, it will merely grow into a tree normally.
- Test 6: If I grow a sapling in Chunk A, then fly around and grow saplings in random nearby chunks, and then go back and grow a sapling on a border to Chunk A, the game eventually crashes.

**Conclusion:** There seems to be a system in place to prevent this crash when the sapling is grown with bonemeal, as the crash never happens when using bonemeal. It also seems to grow normally, both naturally and with bonemeal, when the neighbouring chunk has been interacted with recently.  _The game only crashes when there's a jungle or spruce sapling on a border to a chunk that hasn't been "used" by OTG very recently, and that sapling tries to grow naturally._

**Comment by MCPitman** [comment] 2019-10-28 18:10
Thanks. It would have been more useful to test without other mods and using the OTG release version.

**Comment by authvin** [comment] 2019-10-28 18:21
Yeah, I only realised after I'd finished testing and written everything down. I redid all the testing steps quickly and confirmed it behaves the same with release version and no other mods installed. Did notice that I switched north and south in test 5, it's the south side that grows it normally.

**Comment by PG85** [comment] 2019-10-28 23:05
Have included a fix for this in v8.1_r1, to be released on the OTG Discord's dev channel asap. Will be in the v8.1 release.

**Closed as completed by PG85** 2019-10-28 23:05 UTC

**Comment by authvin** [comment] 2019-10-30 13:47
Tested and confirmed that the problem is indeed fixed for every case I found before. Thanks PG ^^

**Comment by PG85** [comment] 2019-10-30 23:03
Sweet, thanks for reporting! :)
