### ISSUE TITLE
Odd looking/broken chunks with OTG 8 and Farseek 2.4

### ISSUE THREAD

**Issue by Tiscan76** [PG85/OpenTerrainGenerator#388] opened 2019-11-28 16:41 UTC
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2_v8_3_r4 (also tested using 8.2)

#### Forge or Spigot Versions
Forge 14.23.5.2847

#### What other plugins are you running?
Biome Bundle v6.1, Journey Map 5.5.5, Farseek 2.4, Streams 0.4.7

#### Description
When I move around in a new world while the latest version of Farseek (and Streams) is installed, some of the chunks that are generated are kinda "broken".

This happens both if you just fly into new terrain or if you teleport using the /tp command (/tp makes it easier to see the "broken" chunks as they will usually be near your target-loacation).

You can see the effect in this picture:

![broken_chunk](https://user-images.githubusercontent.com/40497203/69821567-5e54b400-1204-11ea-951d-6429aefd34cb.jpg)

I tested Farseek with other mods that mess with world-generation (BoP, Traverse, etc.) and it didn't seem to happen then, so I guess it's an OTG-problem.

From what I can tell, the terrain itself generates just fine - it won't suddenly change elevation or anything like that -> the "structure" of the terrain seems to be correct. Ores, Caves, etc. that are undergorund also seem to be fine (no sudden gaps or anyhting like that). Apparently the only thing going wrong is the "ground cover". So instead of a layer of grass on the surface you end up getting a layer of stone.

In some places it looked as if the ground-cover from the neighbouring biome was used instead of the correct one. For example I had a situation where some biome with a lot of podzol was next to a mountainous biome and the "broken" chunk was in the mountainus part. The surface of the "broken" chunk was completely covered in podzol instead of stone.

**Comment by PG85** [comment] 2019-12-01 16:10
Hey @Tiscan76 , thanks for reporting this. Looks like a problem with blocks not being replaced properly. Not sure this is mod-compatibility issue, this has been reported more often. Will group issues/reports and look at this as soon as it has prio.

**Comment by PG85** [comment] 2019-12-01 16:12
Moving to support for now, need a minimal test setup for this. Preferably without any other mods (or only minimal mods to recreate the issue). Need a preset, seed and coordinates where the problem is reproduced so I can debug it.

**Comment by Tiscan76** [comment] 2019-12-01 19:48
I can't guarantee that it will always happen but what I did is this:

* Create a modpack with just OTG, BB, Farseek 2.4 and Streams 0.4.7
* Create a new world using the seed "Farseek"
* Teleport to 11000 150 -11000 -> i did 3 tests and in all 3 cases my Minecraft lagged like hell and when it finally showed something, there were 2 messed up chunks (funny thing is, at 11000 150 11000 there is another very funky piece of terrain-gen -> 1 chunk of what looks like Mesa in an Ice-Plains biome - this will also always happen on my test-setup but IDK if it's the same bug)

The problem is: while i can always reproduce the bug by teleporting around using `/tp ~1000 ~ ~1000`, it usually happens at different coords. Only the 11000/-11000 and 11000/11000 have been consistent so far.

Hope this helps.

**Comment by Tiscan76** [comment] 2020-01-17 13:48
Just a quick update: while i was able to reproduce the bug easily in any verison prior to 9.0, those messed up chunks did not happen in in my first tests using the 9.0 dev-release. I ported around 20-30 times and so far, everything is fine.

**Comment by PG85** [comment] 2020-01-17 14:42
Hey @Tiscan76 , thanks for reporting back! Will move this into the v9 release milestone and close it for now. If you see this happening again, feel free to reopen or create a new issue.

**Closed as completed by PG85** 2020-01-17 14:42 UTC
Labels: Bug - Issue, Forge, World/Biome/Terrain, Support
