### ISSUE TITLE
OTG+Mob mods - Incompatibility issue with water mobs 

### ISSUE THREAD

**Issue by TitusArmillius** [PG85/OpenTerrainGenerator#109] opened 2018-01-03 12:30 UTC
I've done some extensive testing with OTG, CMS (custom mob spawner) & Mo' Creatures. I have found that while vanilla and custom biomes do accept Mo' creatures mobs/animals, no biome will spawn water creatures in water. Strangely enough, when I removed the water, Mo' creatures fish have spawned on the ground, reportedly sharks and other creatures have also spawned like this. For some reason the game is refusing to spawn Mo'creatures in water.

Here are a list of facts which I discovered:

Default settings (OTG + Mo'Creatures):

-Mo'creatures only spawn in vanilla biomes.

-Vanilla creatures spawn in both vanilla and non-vanilla biomes.

-No water creatures spawn in either vanilla or non-vanilla biomes.

-Mo'creatures & Vanilla creatures spawn in-spite of individual biome mob control settings in vanilla biomes.

Modified settings (OTG + CMS + Mo'Creatures):

-Mo'creatures only spawn on land when vanilla creatures spawning is disabled via CMS config and no creatures are specified in the OTG biome configs.

-Water creatures do not spawn in vanilla biomes even if the biome has been added to the specific creatures biome group in the CMS config, increasing the water creature spawn frequency has no effect on this.

-Water creatures will spawn in ocean biome if the surface is below Y63 and there is no water.

-Water creatures will not spawn in water in any vanilla or non-vanilla biome regardless of where they are specified to spawn in such biome from either the CMS or OTG config.

**Comment by MCPitman** [comment] 2018-01-06 15:07
Didn't see this had already been posted, see https://github.com/PG85/OpenTerrainGenerator/issues/111 for more info and confirmation that it is not caused by CMS.

**Comment by PG85** [comment] 2018-01-20 11:01
Hey, I did some testing with CMS and Mo'Creatures without OTG. When I install both and create a new world, no mobs spawn, not even vanilla ones. When I remove CMS, most mobs spawn, but no water creatures except squid. Am I doing something wrong?

**Comment by Misunderstood-Wookiee** [comment] 2018-01-21 12:47
@PG85 
An older version of CMS the one listed on curse is outdated it has no terrain generator support, so it overrides vanilla spawns in biomes, this has been fixed in the version available on the official website for [MoCreatures ](http://www.mocreatures.org/downloads) it now has an option to enable or disable vanilla mob spawns.

**Comment by PG85** [comment] 2018-01-31 19:07
Hey, I investigated this a bit more and it looks like Moc handles mob spawning outside of the vanilla spawning mechanics (I could not make them work with MoC water creatures even after hacking them to allow them to pass the spawn checks), this appears to not be working for OTG worlds for some reason. Unfortunately MoC doesn't share code, will skip this bug for the next release (fixing the last bug now) and continue investigating later.

**Comment by darchitectlp** [comment] 2018-02-27 05:34
Hey, @PG85 if you need a temporary work around, I've had luck using McJty's InControl. I just add this to potentialspawn.json:

```json
[
  {
    "dimension": 0,
    "biome": "Ocean",
    "block": "minecraft:water",
    "mobs": [
      {
        "mob": "mocreatures:shark",
        "weight": 100,
        "groupcountmin": 1,
        "groupcountmax": 4
      }
    ]
  }
]
```

Sharks are spawning :)  Getting ready to try and add jellyfish back. Then dolphins.

**Comment by xorinzor** [comment] 2018-06-05 16:38
@darchitectlp doesn't seem to be working for me, additionally gonna just put a reference to my issue too. It's kinda the same, but different. #170

**Comment by Xenoamor** [comment] 2018-09-04 18:34
+1

**Comment by HyperGaming18** [comment] 2018-09-07 01:59
+2

**Comment by PG85** [comment] 2019-08-19 15:35
Unfortunately too big to handle for v8 will do after 1.13, closing this, will use #170.

**Closed as completed by PG85** 2019-08-19 15:35 UTC
Labels: Feature, Forge, Mod Compatibility, Mob/Entity Spawning
