### ISSUE TITLE
Bug: 1.16.x - Borders/Isles for temperature-specific Oceans don't work

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#830] opened 2021-08-07 01:45 UTC
When using the new ocean features (in the worldconfig), Frozen Oceans are way more common than any other ocean type for some reason. To the point where it's actually difficult to find the other ocean types.

Example from the default preset (yellow area is frozen ocean, pink is other oceans):
![image](https://user-images.githubusercontent.com/23154920/128584121-6a700be8-7a3a-4deb-967b-719630fbdac8.png)

In this example, the only place frozen ocean is used is in the worldconfig, here:

```
DefaultOceanBiome: Ocean

DefaultWarmOceanBiome: Warm Ocean

DefaultLukewarmOceanBiome: Lukewarm Ocean

DefaultColdOceanBiome: Cold Ocean

DefaultFrozenOceanBiome: Frozen Ocean
```

**Comment by PG85** [comment] 2021-08-07 10:23
Related to #829 , looks like this is due to isle/border biome settings. When using landrarity 1 and no isles/borders for VV4, changing OceanBiomeRarity from 1 to 10 does: 
![afbeelding](https://user-images.githubusercontent.com/6781444/128597044-11e573d0-3896-4085-b9e3-a86bfbe41b40.png)
When using isles/borders, it does: 
![afbeelding](https://user-images.githubusercontent.com/6781444/128597051-ab5b1072-282c-4e3d-90b6-b8e960257798.png)

If there's a problem with isles/borders, please update this issue. If this is somehow a config error / expected behaviour, please close it.

**Comment by PG85** [comment] 2021-08-07 13:14
Isles and borders have the same problems when used with Oceans, the biome generator only applies temperature dependent ocean biomes after all land/border/isle biomes have been placed. At that point, the default Ocean biome is replaced to the temperature-specific ocean biomes. Will look at implementing proper borders/isles for oceans for 1.0.0.

**Comment by FrankTCA** [comment] 2021-11-05 23:47
Appears to be a duplicate of #615

Reopen if not.

**Closed as completed by FrankTCA** 2021-11-05 23:47 UTC
Labels: Bug - Issue, World/Biome/Terrain, Common
