### ISSUE TITLE
OpenTerrainGenerator not setting generator for default world, using BiomeBundle

### ISSUE THREAD

**Issue by FlatoutDude** [PG85/OpenTerrainGenerator#153] opened 2018-04-02 22:13 UTC
Hello, I'm having an issue with a fresh install of OTG, i just created a server, followed the instructions, and every time it gives me this error when i reset the world when trying to fix the issue:
(I've tried redownloading, re-extracting, and renaming the world folder and in the configs like the instruction shows.)

[17:07:32] [Server thread/ERROR]: [OpenTerrainGenerator] Could not set generator for default world 'Biome Bundle': Plugin 'OpenTerrainGenerator v1.12.2 v6
java.lang.ExceptionInInitializerError: null
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:131) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1224) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-68b4fb6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:260) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-68b4fb6]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-68b4fb6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-68b4fb6]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:39) ~[?:?]
	... 14 more
Caused by: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:33) ~[?:?]
	... 14 more

**Comment by MCPitman** [comment] 2018-07-29 15:03
Looks like this is caused by incorrect installation, probably by not setting world type to OTG.

No issues like this have been reported by other users so closing this for now.

**Closed as completed by MCPitman** 2018-07-29 15:03 UTC

**Comment by arlidencrow** [comment] 2018-10-27 03:47
I have the same issuse

**Comment by Dunemask** [comment] 2020-01-27 03:08
I have confirmed the issue is a problem with the java instillation, OpenJDK8 is not compatible, make sure your java version is the latest

**Comment by FlatoutDude** [comment] 2020-01-27 05:18
except i don't use OpenJDK8.. i use JRE8, and i'm positive it was up to date at the time of posting.

**Comment by Dunemask** [comment] 2020-01-27 13:01
I only use the JDK so i wouldn’t know, however the error was definitely
caused by an incomplete java instillation. I know back then java was
changing a lot update to update for security patches so there’s a chance
that section of the JDK wasn’t in the official JRE release. One thing’s for
sure, people telling me i had just installed it wrong was infuriating 😂
--

**Comment by legendcuzican13** [comment] 2024-05-27 02:29
For anyone who still has this issue, I fixed it by switching from Java 17 to Java 8 on my 1.12.2 server.

**Comment by Hallowee12345** [comment] 2025-05-23 15:31
> For anyone who still has this issue, I fixed it by switching from Java 17 to Java 8 on my 1.12.2 server.
Thank you so so much, this works and now I can play this cool world gerneation with my friends.
