### ISSUE TITLE
OTG + MV - Vanilla ocean monuments spawn in the default vanilla seed location, overriding custom terrain.

### ISSUE THREAD

**Issue by mibby** [PG85/OpenTerrainGenerator#48] opened 2017-07-29 03:10 UTC
RE: https://github.com/PaperMC/Paper/issues/807

**Comment by MCPitman** [comment] 2017-07-31 18:19
Are you experiencing this when using an OTG world with multiverse? As this doesn't happen under normal circumstances on Spigot.

**Comment by PG85** [comment] 2017-08-01 10:25
Hey, thanks for the report. I'm not sure what you did there but generated chunks should never be re-generated or populated twice. I've not been able to reproduce this in any way.

**Comment by MCPitman** [comment] 2017-08-01 10:32
Actually, the ocean monuments are the only structures that vanilla
Minecraft will "retro-generate" into already generated chunks.

**Comment by PG85** [comment] 2017-08-01 10:47
Ok thanks, I stand corrected. This appears to be a very specific bug with multiverse, unfortunately the to-do list is pretty full atm. May take a while before I have time to look at this (unless a lot more people start reporting it).

**Comment by mibby** [comment] 2017-08-03 20:01
I had the monuments retro-regenerate on top of the world after uninstalling multiverse once the world was pre-generated in full. Even pre-generated a world without multiverse. So I assume it is just the 3 minute vanilla chunk inhibited timer it checks for before it generates everywhere.

**Comment by MCPitman** [comment] 2017-08-03 21:21
This doesn't happen with standard Spigot, so seems to be an issue on Paper Spigot's end if it's happening without Multiverse.

**Comment by PG85** [comment] 2019-06-10 07:57
Closing this as an old paper-spigot issue, feel free to re-open if it's still happening.

**Closed as completed by PG85** 2019-06-10 07:57 UTC
