### ISSUE TITLE
Sapling Listener / Sapling Grow server crash R8 V8

### ISSUE THREAD

**Issue by darkmushroom** [PG85/OpenTerrainGenerator#351] opened 2019-10-20 22:19 UTC
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [x] Vanilla_Vistas 1.1

#### OTG Version
- [x] 1.12.2_v8_r8

#### Forge or Spigot Versions
Forge 14.23.5.2847

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3748470/latest.log)
[crash-2019-10-20_16.09.00-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3748472/crash-2019-10-20_16.09.00-server.txt)

#### What other plugins are you running?
(Listed in crash report)

#### Description
Looks like the long-running sapling grow issue is back:
java.lang.NullPointerException: Exception ticking world
	at com.pg85.otg.forge.events.SaplingListener$SaplingGrower.isSameSapling(SaplingListener.java:102)

**Comment by MCPitman** [comment] 2019-10-27 19:22
Duplicate of #361

**Closed as completed** 2019-10-28 21:11 UTC
