### ISSUE TITLE
Better With Mods: Forge Event for MapGenBase 

### ISSUE THREAD

**Issue by primetoxinz** [PG85/OpenTerrainGenerator#157] opened 2018-04-11 22:00 UTC
Hello,
It was brought to my attention that some of the world gen in my mod, Better With Mods, does not work with OTG. 
It appears this is due to the lack of posting of the InitMapGenEvent which allows overriding the MapGenBase object before it generates.

This can be done through `TerrainGen.getModdedMapGen` whenever a MapGenBase is initialized.

BWM specifically uses quite a few of these, so if you could make sure to post the various EnumTypes that would help our mods be much more compatible

Thanks ahead of time

**Comment by PG85** [comment] 2018-06-13 21:01
Hey primetoxinz,

Thanks for reporting this and sorry for the late reply. Will look at this as soon as I have the time. Working on a big new feature atm though, will need to finish and release that first.

**Comment by PG85** [comment] 2019-06-15 01:15
Have added getModdedMapGen for villages/monuments/mineshafts/mansions/strongholds/scattered features. Not sure it'll work as intended, still have to test. Will be in v7_r25.

**Closed as completed by PG85** 2019-06-15 01:15 UTC
Labels: Bug - Issue, Forge, Mod Compatibility
